micronaut:
  application:
    name: ingresso
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update


endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

#Cassandra

cassandra:
  default:
    basic:
      contact-points:
        - ${cassandra_contact_points:localhost}
      session-keyspace: "mykeyspace"
      load-balancing-policy:
        local-datacenter: ${cassandra_local_datacenter:datacenter1}

#Verificar o erro ao habilitar health
endpoints.health.cassandra.enabled: false

#cassandra:
#  default:
#    advanced:
#      metadata:
#        schema:
#          enabled: false
#    basic:
#      contact-points:
#        - "127.0.0.1:9042"
#        - "127.0.0.2:8042"
#      load-balancing-policy:
#       local-datacenter: datacenter1


# - ${cassandra_contact_points:localhost}
# session-keyspace: ${cassandra_session_keyspace:}