micronaut:
  application:
    name: ingresso


endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

#Cassandra

cassandra:
  default:
    basic:
      contact-points:
        - ${cassandra_contact_points:localhost}
      session-keyspace: "mykeyspace"
      load-balancing-policy:
        local-datacenter: ${cassandra_local_datacenter:datacenter1}

#Health Cassandra
endpoints.health.cassandra.enabled: true