micronaut:
  application:
    name: ingresso
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update


endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

#Cassandra

cassandra:
  default:
    basic:
      contact-points:
        - ${cassandra_contact_points:localhost}
      session-keyspace: "mykeyspace"
      load-balancing-policy:
        local-datacenter: ${cassandra_local_datacenter:datacenter1}

#Health Cassandra
endpoints.health.cassandra.enabled: true